PACKAGE_NAME="psvr2"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="psvr2"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make clean KDIR=${kernel_source_dir}"

AUTOINSTALL="yes"
